version: '2'
services:
  web:
    build: ./web
    ports:
      - 80:8080
    working_dir: /chat_web
    command: npm run dev
    volumes:
      - ./web:/chat_web
    links:
      - api
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - 8000:80
    working_dir: /chat_api
    command: mix run --no-halt
    volumes:
      - ./api:/chat_api
    depends_on:
      - pg-hack-trip # wait to be starded

  pg-hack-trip:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=chat_web_repo
      - MIX_ENV=pg

  ngrok:
    image: wernight/ngrok
    command: ngrok http web:8000
    depends_on:
      - web
