version: '2'
services:
  web:
    build: ./web
    ports:
      - 80:8000
    working_dir: /hackaton_viagens_web
    command: npm run dev
    volumes:
      - ./web:/hackaton_viagens_web
    links:
      - api
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - 8000:8000
    working_dir: /hackaton_viagens_api
    command: mix run --no-halt
    volumes:
      - ./api:/hackaton_viagens_api
    depends_on:
      - rethinkdb # wait to be starded

  rethinkdb:
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015

  ngrok:
    image: wernight/ngrok
    command: ngrok http web:8000
    depends_on:
      - web

