version: '2'
services:
  web:
    image: hackathon-viagens-web
    build:
      context: ./web
      dockerfile: ./web/Dockerfile.prod

  api:
    image: hackathon-viagens-api
    build:
      context: ./api
      dockerfile: ./api/Dockerfile.prod

  ngrok:
    image: hackathon-viagens-ngrok
    build:
      context: .
      dockerfile: Dockerfile.ngrok

