apiVersion: v1
kind: Service
metadata:
  name: hackathon-viagens
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: hackathon-viagens
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: hackathon-viagens
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hackathon-viagens
    spec:
      containers:
      - name: hackathon-viagens
        image: gcr.io/yebo-project/hackathon-viagens:latest
        ports:
        - containerPort: 443
        - containerPort: 80

